### PR TITLE
Show File and Directory History as a LineChart

### PR DESCRIPTION
**Pull request by mbehzad**
When a Module or Directory is hovered on in the SunBurstChart, the size history of that Module, or all Modules in that directory or sub directories is shown as a line chart, right to the Breadcrumb (on small media queries, it'll be beneath the breadcrumb).

file-histpry

### CODE REVIEW

**Comment by roachjc** [comment]
Hi @mbehzad I really like this idea - nice one! One thought ... would it make sense to hide the mini line chart for node-modules? 

My thinking is that we are not concerned with third party module sizes changing over time, but whether or not they are included or not.

I mention this also because with the data I am using, all node-modules just show a flat line (i.e. without data). The application files are properly represented.

Any thoughts?

screen shot 2017-11-11 at 18 58 30
screen shot 2017-11-11 at 18 58 55

**Comment by mbehzad** [comment]
Hi @roachjc, I think what could be interesting is to see at which build a dependency was added to the project, which would be recognizable with a jump in the mini line chart. But probably the size of a 3rd party library or framework changes much much slower than the 1st party code. Therefore not so interesting. Except when the library usage is heavily tree shaken and in the line chart it can be seen that more and more modules are used from a utils library e.g. lodash ...

Regarding the flat lines, the issue is that in `StarburstContainer#dataParser`, the file paths are converted with replacing `-` with `_` and `/` with `-`. This can not be 100% reverted. namely for the `_` which could originally be `_` or `-`. That’s why in the breadcrumb you see "node-modules" instead of "node_modules". And the mini line chart can't find the correct sizes. I'm going to try to fix that in the next days.

**Comment by mbehzad** [comment]
i updated the code. if you like, you could have a look at it.

**Comment by roachjc** [comment]
Thanks for this @mbehzad! Looks good 😀 Can I ask a favor - for future PRs could you use AirBnB's styleguide please? I know it's not all totally compliant currently, but would love to keep it as close as we can for all future commits. No need to go back and amend what's already merged / PR'd. We can update those as we go.

**Pull request merged**
